/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks;

import org.junit.Test;
//import static org.junit.Assert.*;

public class MicrohooksTest {
    @Test public void testSomeLibraryMethod() {
        //Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
}
