/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks.examples.micronaut;

import io.microhooks.core.MicrohooksApplication;

@MicrohooksApplication(container="micronaut")
public class SinkMicroservice {
    
    public static void main(String[] args) {

    }
}
