/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks;

import java.lang.annotation.Annotation;
import java.lang.reflect.Method;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class Test {

    @Autowired
    TestRepository repo;
    
    public static void main(String[] args) {
        SpringApplication.run(Test.class, args);
    }

    @GetMapping("/hello")
    public String sayHello() {
        TestEntity entity = new TestEntity();
        entity.setName("Hi!");
        entity = repo.save(entity);
        entity.setName("Hello");
        entity = repo.save(entity);
        entity.setName("Hello world!");
        entity.setName("Hello again!");
        repo.save(entity);
        return "Hello!";
    }
    
}
