/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks;

import java.lang.annotation.Annotation;
import java.lang.reflect.Method;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class Test {

    @Autowired
    TestRepository repo;
    
    public static void main(String[] args) {
        SpringApplication.run(Test.class, args);
    }

    @GetMapping("/hello")
    public String sayHello() throws Exception {
        StringBuilder sb = new StringBuilder();
        Annotation[] annotations = TestEntity.class.getAnnotations();
        for (Annotation annotation : annotations) {
            Class<? extends Annotation> type = annotation.annotationType();
            sb.append(type.getName() + " ");
            for (Method method : type.getDeclaredMethods()) {
                Object value = method.invoke(annotation, (Object[])null);
                if (value instanceof Class<?>) {
                    System.out.println(" " + method.getName() + ": " + ((Class<?>)value).getName());
                }
            }
        }

        TestEntity entity = new TestEntity();
        entity.setName("Hi!");
        repo.save(entity);
        
        return sb.toString();
    }
    
}
