/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks.examples.micronaut;


import io.micronaut.runtime.Micronaut;


public class SinkMicroservice {
    
    public static void main(String[] args) {
        Micronaut.run(SinkMicroservice.class, args);
    }
}
