/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks.examples.micronaut;

import io.microhooks.core.MicrohooksApplication;
import io.microhooks.core.ContainerType;

import io.micronaut.runtime.Micronaut;

@MicrohooksApplication
public class SinkMicroservice {
    
    public static void main(String[] args) {
        Micronaut.run(SinkMicroservice.class, args);
    }
}
