/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks.examples.quarkus;

import io.microhooks.core.MicrohooksApplication;
import io.microhooks.core.ContainerType;

@MicrohooksApplication(name="SinkMicroservice2", container=ContainerType.QUARKUS)
public class SinkMicroservice {

    public static void main(String[] args) {
        
    }
}
