/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks.examples.quarkus;

import io.microhooks.core.MicrohooksApplication;

@MicrohooksApplication(container="quarkus")
public class SinkMicroservice {

    public static void main(String[] args) {
        
    }
}
