/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks.tests.spring.raw;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SourceMicroservice {
   
    public static void main(String[] args) {
        SpringApplication.run(SourceMicroservice.class, args);
    }
    
}
