/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks.internal.providers.rabbitmq;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
