/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.microhooks.extensions.environments.micronaut;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
